### ISSUE TITLE
Is there a way to make this example more concise?

### ISSUE THREAD

**Issue by trusktr** [propjockey/css-media-vars#1]
**First of all, this is amazing! It is super useful!!**

I have the following, which works:

```css
@import 'https://unpkg.com/css-media-vars@1.0.1/css-media-vars.css';

.face_container {
	--margin-left-mobile: var(--media-xs) 0;
	--margin-left-desktop: var(--media-lte-sm) 20px;
	--margin-top-mobile: var(--media-xs) 20px;
	--margin-top-desktop: var(--media-lte-sm) 0;
	margin-left: var(--margin-left-mobile, var(--margin-left-desktop));
	margin-top: var(--margin-top-mobile, var(--margin-top-desktop));
}
```

Is there a more concise way to write it?

I guess maybe another question is can we make the equivalent of a `NOT` operator, and flip the mobile-desktop values, instead of writing two new variables, or something?

Based on your circuit example with the number display, I think the answer is we can. The syntax just isn't fully clear to a casual CSS user like me. :)

**Comment by trusktr** [comment]
Oops, my example should actually be

```css
@import 'https://unpkg.com/css-media-vars@1.0.1/css-media-vars.css';

.face_container {
	--margin-left-mobile: var(--media-xs) 0;
	--margin-left-desktop: var(--media-gte-sm) 20px;
	--margin-top-mobile: var(--media-xs) 20px;
	--margin-top-desktop: var(--media-gte-sm) 0;
	margin-left: var(--margin-left-mobile, var(--margin-left-desktop));
	margin-top: var(--margin-top-mobile, var(--margin-top-desktop));
}
```

with `gte` instead of `lte`. That's what I meant. In this case, it is easy to achieve two discrete size ranges that don't overlap because I'm using `xs` and `gte-sm`, but harder for other splits (see #2).

**Comment by trusktr** [comment]
Oops, I updated my last comment (in case you're reading email). Forgot to replace `gte` with `lte`. Edited the previous comment.

**Comment by JaneOri** [comment]
Hey @trusktr ! 

I think I see the confusion about the docs now, `--media-xl` doesn't have an upper range, it starts at 1800px with no max. Similarly, `--media-xs` has no minimum.

Every range should be possible with what's there - is there a specific scenario you're concerned about?

I'll update the docs to show specifically what media queries they correspond to at least, that should help. Will update here when I've completed that.

Thank you!

**Comment by JaneOri** [comment]
Alrighty, I've updated the docs - please let me know if that helps clarify things!

It now includes a visual guide too:
<img src="https://propjockey.github.io/css-media-vars/breakpoints.png" alt="visual guide to breakpoint ranges in css-media-vars">

Thank you!

**Comment by trusktr** [comment]
@James0x57 Thanks, that table is definitely helpful. Easier than looking in the source!

I knew that `--media-xl` has no upper limit, and `--media-xs` has no lower limit. 

I'm was wondering if I wrote the example the shortest way possible (apart from reducing variable name length).

**Comment by JaneOri** [comment]
Ahhh, okay, here's what you put:
```css
.face_container {
	--margin-left-mobile: var(--media-xs) 0;
	--margin-left-desktop: var(--media-gte-sm) 20px;
	--margin-top-mobile: var(--media-xs) 20px;
	--margin-top-desktop: var(--media-gte-sm) 0;
	margin-left: var(--margin-left-mobile, var(--margin-left-desktop));
	margin-top: var(--margin-top-mobile, var(--margin-top-desktop));
}
```
This is great and it's explicit about covering all your bases. It can be made more simple though, like so:
```css
.face_container {
	--margin-left-mobile: var(--media-xs) 0;
	--margin-top-mobile: var(--media-xs) 20px;
	margin-left: var(--margin-left-mobile, 20px);
	margin-top: var(--margin-top-mobile, 0);
}
```
basically it's saying "if it's extra small, use these values, else use the fallback"

Does that help? :)
