### ISSUE TITLE
idea: variables like `--media-gt-sm`

### ISSUE THREAD

**Issue by trusktr** [propjockey/css-media-vars#2]
I noticed there are no `--media-lt-*` or `--media-gt-*` variables. I think those would be useful.

F.e. instead of

```css
.foo {
	--layout-mobile: var(--media-lte-sm) column;
	--layout-desktop: var(--media-md-lg, var(--media-xl)) row; /* not sure I did it right, but there isn't a variable that includes everything including anything gte xl, so this is complicated */
}
```

we could write

```css
.foo {
	--layout-mobile: var(--media-lte-sm) column;
	--layout-desktop: var(--media-gt-sm) row;
}
```

We can't use `--media-gte-sm` because then it overlaps, whereas we want a non-overlapping distinction.

In the first example, I don't think `var(--media-md-lg, var(--media-xl)) row` even works, because then the final result is always `initial`, right? So with the lack of the `-gt-` and `-lt-` variables, a casual CSS user might not know exactly how to achieve that.

**Comment by JaneOri** [comment]
Hey! Thank you for checking this out @trusktr !

I didn't include `--media-gt-sm` (or similar) because it would be the same as `--media-gte-md`.

So this:
```css
.foo {
  --layout-mobile: var(--media-lte-sm) column;
  --layout-desktop: var(--media-md-lg, var(--media-xl)) row;
  /* not sure I did it right, but there isn't a variable that includes everything including anything gte xl, so this is complicated */
}
```
becomes this:
```css
.foo {
  --layout-mobile: var(--media-lte-sm) column;
  --layout-desktop: var(--media-gte-md) row; /* includes everything that's not small or extra small (no max limit) */
}
```

Does that help? I'm open to suggestions for what the docs should say around those too!

**Comment by trusktr** [comment]
Oh riiight. That makes sense; I totally overlooked it. Wdyt if we were to have gt-sm as alias of gte-md, etc? (Like in languages where we can choose between `>` or `>=`).

**Comment by JaneOri** [comment]
You can include this CSS on your site:
```css
html {
  --media-gt-sm: var(--media-gte-md);
}
```
and it will be available as an alias everywhere!
Though note that the "--media-" prefix is meant to be a namespace for the library (like "--aug-" in augmented-ui or "--bs-" in the newest bootstrap) so you'll have to be aware if updates come that you might be stepping on toes then.

That said, I do not intend to add aliases since it will bulk up the code and they're not necessary so creating them yourself is likely a safe thing in this case!

Make sense? Anything else I can help with? :)
